name: release

on:
    push:
        branches:
            - main

jobs:
    gh-pages:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn

            - name: Install dependencies
              run: yarn

            - name: Build project
              run: yarn build

            - name: Publish on Github Pages
              uses: crazy-max/ghaction-github-pages@v2.5.0
              with:
                  build_dir: dist
                  fqdn: debstudioestetico.it

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
